apiVersion: v1
kind: Service
metadata:
  name: config-server
  labels:
    app: config-server
spec:
  type: ClusterIP
  selector:
    app: config-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8888
